import test from 'node:test';
import assert from 'node:assert/strict';
import { BattleController } from '../src/battle-controller.js';
import { MockNarrator } from '../src/adapters.js';
import sample from '../sample-data/dielang-xuanchaojue.json' with { type: 'json' };
const scene=()=>({scene:{location:'Resource test',time:'Now'},actors:{player:{id:'player',name:'主角',visibleInfo:{},resources:{qi:12},techniques:[]},enemies:[]},semanticState:{statuses:[],effects:[],positions:{},control:'均势'},registry:[sample],resourceRules:[{actorId:'player',resource:'qi',min:0,max:12,ruleRefs:['world.qi']}]});
function judgement(request,delta){const value=request.context.actors.player.resources.qi;return{summary:'可见节奏改变',before:request.context.semanticState,after:request.context.semanticState,reason:'按权威资源边界裁定',ruleRefs:['world.qi'],exchange:{playerResult:'真气消耗',opponents:[],environmentResult:'无变化',boundaries:[]},publicEvents:[],resourceChanges:[{actorId:'player',resource:'qi',before:value,after:value-delta,reason:'世界规则定义的本次消耗',ruleRefs:['world.qi']}]};}
test('world-defined resources accumulate across two rounds and rewriting never charges again',async()=>{let calls=0;const adjudicator={async judge(request){calls+=1;return judgement(request,calls===1?3:2);}};const c=new BattleController({adjudicator,narrator:new MockNarrator()});c.importScene(scene());c.start();await c.submit({actionId:'resource-1',label:'第一行动'});assert.equal(c.state.actors.player.resources.qi,9);c.continueNext();await c.submit({actionId:'resource-2',label:'第二行动'});assert.equal(c.state.actors.player.resources.qi,7);await c.rewrite('resource-2');assert.equal(c.state.actors.player.resources.qi,7);assert.equal(calls,2);await c.submit({actionId:'resource-2',label:'重复行动'});assert.equal(calls,2);});
for(const problem of['stale-before','no-rule','out-of-range','duplicate'])test(`invalid resource settlement ${problem} is refused before committing`,async()=>{const adjudicator={async judge(request){const result=judgement(request,3);if(problem==='stale-before')result.resourceChanges[0].before=11;if(problem==='no-rule')result.resourceChanges[0].resource='undefined';if(problem==='out-of-range')result.resourceChanges[0].after=-10;if(problem==='duplicate')result.resourceChanges.push({...result.resourceChanges[0]});return result;}};const c=new BattleController({adjudicator,narrator:new MockNarrator()});c.importScene(scene());c.start();await assert.rejects(()=>c.submit({label:'非法资源'}),/资源/);assert.equal(c.state.actors.player.resources.qi,12);assert.equal(c.state.history.filter((r)=>r.status==='committed'||r.status==='complete').length,0);});
